# Generated by Django 6.0.3 on 2026-03-16 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='sobrenome',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Sobrenome'),
        ),
    ]
